export const plans = [
        {
            id:"basic",
            name: "Basic Plan",
            price: "$0",
            description: "per editor/month billed monthly",
            features: [
                "30h Fast generations",
                "Unlimited Relaxed generations",
                "General commercial terms",
                "Access to member gallery",
                "Optional credit top ups",
                "3 concurrent fast jobs",
                "12 concurrent fast jobs",
                "Access to member gallery",
                "Optional credit top ups",
            ],
            buttonText: "Current Plan",
            isPopular: false,
        },
        {
            id:"pro",
            name: "Stander Plan",
            price: "$30",
            description: "per editor/month billed monthly",
            features: [
                "15h Fast generations",
                "Unlimited Relaxed generations",
                "General commercial terms",
                "Access to member gallery",
                "Optional credit top ups",
                "3 concurrent fast jobs",
                "Access to member gallery",
                "Optional credit top ups",
            ],
            buttonText: "Choose Plan",
            isPopular: true,
        },
        {
            id:"premium",
            name: "Unlimited Plan",
            price: "$120",
            description: "per editor/month billed monthly",
            features: [
                "60h Fast generations",
                "Unlimited Relaxed generations",
                "General commercial terms",
                "Access to member gallery",
                "Optional credit top ups",
                "3 concurrent fast jobs",
                "12 concurrent fast jobs",
            ],
            buttonText: "Choose Plan",
            isPopular: false,
        },
    ];