import {  Poppins,Montserrat,DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const poppins = Poppins({
  weight:['300','400','500','600','700','800'],
  subsets:['latin']
})

const montserrat=Montserrat({
  weight:['300','400','500','600','700','800'],
  subsets:['latin']
}) 

const dm_sans =DM_Sans({
  weight:['300','400','500','600','700','800'],
  subsets:['latin']
})
export const metadata = {
  title: "Vip hires",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
