import { Poppins, Montserrat, DM_Sans, Raleway, Manrope, Roboto, Inter,Anton } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/components/Provider";

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

const raleway = Raleway({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});
const anton = Anton({
  weight: '400',
  subsets: ['latin'],
});

const inter = Inter({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'], // ✅ Added subsets
});

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

const dm_sans = DM_Sans({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

const man_rop = Manrope({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

const roboto = Roboto({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'], // ✅ Added subsets
});

export const metadata = {
  title: "Vip Hires",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative flex flex-col justify-between`}>
        <Providers>


          <Navbar />
          {children}
          <Footer bg={"bg-bggreen"} />
        </Providers>
      </body>
    </html>
  );
}
