import {  Poppins,Montserrat,DM_Sans,Raleway,Manrope,Roboto,Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const poppins = Poppins({
  weight:['300','400','500','600','700','800'],
  subsets:['latin']
})

const raleway = Raleway({
  weight:['300','400','500','600','700','800'],
  subsets:['latin']
})
const inter = Inter({
  weight:['300','400','500','600','700','800']
})
const montserrat=Montserrat({
  weight:['300','400','500','600','700','800'],
  subsets:['latin']
}) 

const dm_sans =DM_Sans({
  weight:['300','400','500','600','700','800'],
  subsets:['latin']
})
const man_rop =Manrope({
  weight:['300','400','500','600','700','800'],
  subsets:['latin']
})
const roboto =Roboto({
  weight:['300','400','500','600','700','800']
})
export const metadata = {
  title: "Vip hires",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} relative  flex flex-col justify-between`}
      >
        <Navbar/>
        {children}
        <Footer bg={"bg-bggreen"}/>
      </body>
    </html>
  );
}
